R/read_excel.R
Fixes #19.
Make extension parsing case-insensitive.
Read .xlsm files as .xlsx.
=> Make extensions case-insensitive and support .xlsm

src/cran.h, src/unix/config.h, src/windows/config.h
I think this is the most elegant (least ugly) way of fixing this. We don't change the actual upstream code but instead mask the illegal functions with the corresponding legal alternatives.
=> Fixes for CMD check

src/xls.c
Wrapped the printing of DEFINEDNAME to prevent printing DEFINEDNAME to the console when reading Excel files with defined name ranges.
=> Fix DEFINEDNAME print out when reading Excel files with a name range

NEWS.md, src/XlsxWorkBook.h
First fruit of my C++ tutoring from @jimhester.
Prevents attempt to read value of a nonexistent attribute (can occur in xlsx written by something other than Excel).
=> Fixes #191, crash on .xlsx written by non-Excel tools with non-standard xml attributes

R/RcppExports.R, src/CellType.h, src/RcppExports.cpp, src/StringSet.h, src/XlsWorkSheet.cpp, src/XlsWorkSheet.h, src/XlsxCell.h, src/XlsxWorkSheet.cpp, src/XlsxWorkSheet.h, tests/testthat/test-missing-values.R
Takes care of #13, and fixes a bug where NA = "1" didn't work for .xls sheets.
=> Support multiple na values

src/xlstool.c
It's not standards compliant to use a va_list in more than one call. Unfortunately this works on _some_ platforms.
See http://stackoverflow.com/questions/9309246/repeated-use-of-a-variadic-function-argument-doesnt-work
=> Fixed invalid use of va_list

src/XlsxWorkSheet.h
After all the recent changes, `rootNode_` was only used in this constructor. So I removed `rootNode_` from the class. But everything else here is still used elsewhere. 
Do I have this right?
1. In general, don't make something part of the class if it doesn't need to be.
2. The naming convention, i.e. was I right to remove the trailing `_` now that `rootNode` only lives in the scope of the constructor? Am I even using the right words?
=> Root node no longer needed in XlsxWorkSheet class

NEWS.md, R/read_excel.R, docs/news/index.html, docs/reference/read_excel.html, man/read_excel.Rd, src/ColSpec.h, src/XlsWorkSheet.cpp, src/XlsWorkSheet.h, src/XlsxCell.h, src/XlsxWorkSheet.cpp, src/XlsxWorkSheet.h, tests/testthat/test-col-types.R
Relates to a "nice to have" mentioned in https://github.com/tidyverse/readxl/issues/198#issuecomment-280669414.
The underlying motivation was to add CELL_UNKNOWN to facilitate on-demand cell-typing (discussed in #285). But then you have to add COL_UNKNOWN to keep the enums happy. And at that point, you might as well exploit it and let people specify some col types and guess others.
I'm going to close #285 and start that effort over, after this gets reviewed and merged.
=> Selective col type guessing; add CELL_UNKNOWN, COL_UNKNOWN

src/libxls/xlstool.h, src/xls.c, src/xlstool.c
libxls clearly anticipates that the string table size might require an unsigned 32 bit integer, e.g.:
https://github.com/tidyverse/readxl/blob/0587f00dcc889bc263b232da4c1951c631b975f3/src/libxls/xlsstruct.h#L240-L246
https://github.com/tidyverse/readxl/blob/0587f00dcc889bc263b232da4c1951c631b975f3/src/libxls/xlsstruct.h#L398-L412
https://github.com/tidyverse/readxl/blob/0587f00dcc889bc263b232da4c1951c631b975f3/src/xls.c#L137
https://github.com/tidyverse/readxl/blob/0587f00dcc889bc263b232da4c1951c631b975f3/src/xls.c#L152
(all these types are defined [here](https://github.com/tidyverse/readxl/blob/0587f00dcc889bc263b232da4c1951c631b975f3/src/libxls/xlstypes.h#L39-L47))
But then it was indexing into the table with a 16 bit integer and therefore vulnerable to getting the wrong strings. It …
=> Use uint32_t to index into xls string table; fixes #129

R/RcppExports.R, src/ColSpec.h, src/RcppExports.cpp, src/XlsCell.h, src/XlsWorkBook.cpp, src/XlsWorkBook.h, src/XlsWorkSheet.h, src/XlsxCell.h, src/XlsxWorkBook.cpp, src/XlsxWorkBook.h, src/XlsxWorkSheet.h, src/utils.h
Main point is to prepare for greater unification of xls and xlsx processing (#284).
This makes the date format handling on the xls side match that from xlsx as closely as possible.
Since I had to read all the docs on numeric/date formatting, I made some other superficial changes:
* "style(s)" --> "format(s)". Because that's really what we mean and using that vocabulary makes it less confusing to read the docs.
* Updated my beloved copy of ECMA-376 Part 1 to the 5th edition and (hopefully) all the associated page numbers.
* Moved some more notes into comments for future re-orientation.
=> Refactor and align date format handling

R/read_excel.R, README.Rmd, README.md, docs/index.html, docs/reference/read_excel.html, docs/reference/readxl_example.html, man/read_excel.Rd, tests/testthat/test-sheets.R
😎
``` r
library(readxl)
read_excel(readxl_example("datasets.xlsx"), range = "mtcars!B1:D5")
#> # A tibble: 4 × 3
#>     cyl  disp    hp
#>   <dbl> <dbl> <dbl>
#> 1     6   160   110
#> 2     6   160   110
#> 3     4   108    93
#> 4     6   258   110
read_excel(readxl_example("datasets.xlsx"), range = "bigfoot!B1:D5")
#> Error: Sheet 'bigfoot' not found
```
=> Accept sheet parsed from `range`; closes #318

src/CellLimits.h, src/XlsWorkSheet.h, src/XlsxWorkSheet.h, tests/testthat/test-n-max.R, tests/testthat/test-skipping.R
#316 = "n_max not honoured if leading empty rows are automatically skipped"
Noticed this problem when finishing off #314, the PR which added rectangular reading. #314 made cell loading more efficient by using CellLimit objects to store and reconcile the target rectangle and data rectangle. All in one pass.
But there's one case where CellLimits is awkward, because you need to know where the data is: when there are leading empty rows AND user specifies `n_max` = maximum number of data rows to read.
In this case, you need to read until you find a row that contains any data at all and adjust the nominal rectangle to start there and end `n_max` rows later.
The next time I refactor things -- maybe during the great xls/xlsx unification -- I will try to put some of this logic into the CellLimits …
=> Don't let implicit skipping of empty rows screw up n_max; fixes #316

cran-comments.md, src/libxls/xlstypes.h
There is an existing warning for readxl:
```
Found the following significant warnings:
./libxls/xlstypes.h:64:23: warning: ISO C++ 1998 does not support 'long long' [-Wlong-long]
```
https://www.r-project.org/nosvn/R.check/r-devel-windows-ix86+x86_64/readxl-00check.html
I also see this with current readxl on win builder -- [example](https://win-builder.r-project.org/6yR7GL6Vry35/00check.log). (r-hub is down right now, but I'm pretty sure I saw it on previous checks there this week.)
This PR adapts existing WIN32 handling in libxls to use `_WIN32`, which is defined for all Windows builds. According to win-builder, this will clear the warning -- [example](https://win-builder.r-project.org/4eee83JYoUfo/00check.log).
I also managed to clear it by adding `-Wno-long-long` to `PKG_CFLAGS` and …
=> Clear warning re: 'long long'

src/XlsWorkSheet.h, src/XlsxWorkSheet.h
This is a minor tweak motivated by speed. Example: for one single large xlsx, created from a single wild-caught xls (>50K rows, >100 cols), this speeds up `read_excel()` by >25%. The speed up for xls version of this sheet is closer to 50%. Highly anecdotal, but seems like a sensible change regardless.
=> Stop guessing if we're already at COL_TEXT

R/read_excel.R
readr/R/tokenizer.R says:
#' @param na Character vector of strings to interpret as missing values. Set this
#'   option to `character()` to indicate no missing values.
=> Change na parameter description to match readr

NEWS.md, src/XlsxWorkBook.h, src/utils.h, src/zip.cpp, tests/testthat/test-compatibility.R
Fixes #435 Be able to read sheets produced by the Los Angeles Police Department
The xlsx produced by LAPD is a very literal implementation of the example on pp65-66 of 5th edition of ECMA:
> Example: The following package represents the minimal conformant SpreadsheetML package as defined by ECMA-376
I used this as motivation to make a major upgrade to how readxl parses the package structure. Basically, readxl previously did not parse it but, rather, assumed a very common default. And the LAPD sheets show that other structures are possible (Excel can open the LAPD files, btw). Now we can read LAPD sheets, while still being able to read all the other weird 3rd party sheets in our test collection 🤞
The main feature of the LAPD sheets is that they do not use an `xl/` subdirectory, whereas …
=> Parse _rels/.rels to get paths to package parts

src/unix/config.h, src/windows/config.h
Regenerated `unix/config.h`. Transferred diffs to `windows/config.h` manually.
R CMD check results from win-builder (devel, release, oldrelease) indicate no problems (no problems related to config, that is ... some compiler warnings but unrelated to this).
=> Config spring cleaning

DESCRIPTION, NEWS.md, R/read_excel.R, tests/testthat/helper.R, tests/testthat/test-col-names.R, tests/testthat/test-compatibility.R, tests/testthat/test-missing-values.R
Resolves #357
Recall previous discussion about name repair, that lead to `tibble::set_tidy_names()`: https://github.com/tidyverse/tibble/issues/217
I would really like to make this change. And I predict that revdep checks will reveal few/no problems with this move in *packages*.
But I also know from the previous release that any change here generates a lot of upset and issues, as people have scripts that are hardwired to whatever the previous name repair strategy was. It also always brings up the usual suggestions to clean up nonsyntactic names. Quoting @hadley from thread linked above:
> I'm not sure what we should do with respect to backward compatibility. I suspect few packages depend on this behaviour; it's going to be more user code. I think as long as there's a clear way to get to …
=> Switch to tibble::set_tidy_names() from tibble::repair_names()

NEWS.md, R/read_excel.R, src/XlsWorkBook.h, tests/testthat/test-read-excel.R
Fixes #476 CP1251 char set in file name
Fixes #370 read_excel on Windows fails to open a file from a UTF-8 encoded path containing special characters
This is a new problem seen with R 3.5, we believe as a result of measures taken in response to [Bug 17120 ](https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=17120):
In a non-UTF-8 locale (basically Windows?), `path.expand()` returns a UTF-8 encoded path, even for non UTF-8 input. readxl pre-processes xls paths via `normalizePath()`, which calls `path.expand()`. And then libxls uses `fopen()`, which expects the path in the native encoding.
We have two choices:
1. Stop using `normalizePath()` on xls files. It's not clear to me why we do this. This code goes back to Day 3 of readxl development, in 2015 …
=> Make sure path is in native encoding

NEWS.md, R/read_excel.R
Fixes #498
Prior to b10a1a80fba57e1e7e515b78f64acf62fd75843a, all xls paths were normalized, but we didn't know exactly why. In b10a1a80fba57e1e7e515b78f64acf62fd75843a, I stopped normalizing xls paths, while solving an unrelated path encoding problem presented by R 3.5.
In discussion around #477, @jimhester said:
"I think doing `enc2native(normalizePath())` on the R side for both xls and xlsx seems the best option."
I am now taking this wise advice.
=> Normalize all paths, prior conversion to native encoding

DESCRIPTION
* Fixes #502
* If we want to avoid having non-https links in DESCRIPTION, we could just remove the link there, since we mention it elsewhere
=> Change rapidxml link to regular http

.github/lock.yml
* Fixes #585.
_n.b._ I've disabled the accompanying comment for the initial round of locks to reduce spam (à la https://github.com/tidyverse/readr/commit/17e51ca83ee133a5eaddb8359c8525d204bbd33b#diff-7761990043d6a34d155f65206eb35214 ). Once the initial round of locks has gone through, I'll enable the message, and switch `daysUntilLock` to 180.
=> Add lock bot.

src/utils.h
Closes #481
I'm not sure we can rely on >millisecond resolution with excel dates. I think that the most you can print them in the cell at is a millisecond resolution, so maybe we could call that the cutoff.
This old discussion says that you can technically input any fractional time, but you can only ever format up to milliseconds. 
"Although h:mm:ss.000 is the most precise custom format supported and recognized for data entry, we can actually input any fractional time."
http://www.tech-archive.net/Archive/Excel/microsoft.public.excel.misc/2009-03/msg04040.html
Before:
``` r
library(readxl)
tmp <- tempfile()
path <- "https://github.com/tidyverse/readxl/files/2008644/test_case.xlsx"
download.file(path, tmp)
df <- readxl::read_excel(tmp)
df[20:30,]
#> # A tibble: 11 x 1
#>    date_time …
```
=> Only round to the millisecond level

DESCRIPTION, R/cell-specification.R, man/cell-specification.Rd
I made some small changes to the cell-specification docs to link to the vignette and generally make the examples clearer.
=> Refresh cell specification docs

src/libxls/locale.c, src/libxls/locale.h, src/unix/config-solaris.h, src/unix/config.h
Older versions of the windows C runtime don't have _create_locale, so
instead we use setlocale and the reset it to the previous locale.
On solaris we just do nothing to change the locale.
Fixes #660
Fixes #661
=> Support installation and loading on windows and solaris

R/excel-sheets.R, R/read_excel.R, R/utils.R, src/XlsWorkBook.h, src/XlsWorkSheet.cpp, src/cpp11.cpp
I'm making this PR to restore symmetry of `read_xls_()` and `read_xlsx_()`. I want their signature and body to be the same (for eventual de-deduplication). The symmetry was lost at the time of the Rcpp --> cpp11 conversion (33c79a58).
General recap of this path handling:
* User's path needs to be normalized to expand, e.g., a leading `~/`. At least for xls, we need to do this (see #498).
* As of R 3.5, `normalizePath()` (`path.expand()`, really) returns UTF-8 encoded output, even if the input was not UTF-8.
* Once we adopted cpp11, it also does automatic conversion to UTF-8 for strings.
* This is fine for xlsx because we ultimately open the file with R (see `zip_buffer()` in [`R/xlsx-zip.R`](https://github.com/tidyverse/readxl/blob/d8f789e173b42cb213b8da14979c11aa300eb38e/R/xlsx-zip.R)). …
=> Push re-encoding of xls path into XlsWorkBook constructor

src/SheetView.h
and other systems that use musl.
The problem is that the internal musl header that defines
`uid_t` and `gid_t` only defines it conditionally, if a macro is set.
This macro is set if the header is included from `unistd.h`,
but not if included from another header.
readxl uses `#pragma once`, so the header will not be included
twice, so `uid_t` might not be defined, if unistd.h is not
included early on.
The same story happens with `struct timeval` and `sys/time.h`.
Closes https://github.com/r-hub/r-minimal/issues/40
=> Fix compilation on Alpine Linux

src/libxls/locale.c
readxl had a pre-existing patch related to R's Windows toolchain(s), around some locale-handling code introduced in libxls 1.6.2.
Patch was originally applied before Rtools 4.2 and UCRT was on the horizon. Most recently touched in 1430c78a6286851d4b24459cdb9c32f1b12e1bb0.
Recent `check_win_devel()` and CRAN submissions revealed that the patch needed a refresh for R-devel (will become 4.2), though the relevant tests only fail when the system language is set to German or, presumably, other non-English languages.
Main things to note re: where this PR ended up:
* Current patch is applied as narrowly as possible, i.e. only when we detect readxl is being compiled with Rtools 3.5.
* I fixed what I suspect was a pre-existing infelicity, where a set & capture / restore sequence seemed to have a …
=> Rework libxls locale patch

src/SheetView.h
Reverts the break of the fix from https://github.com/tidyverse/readxl/pull/687 in https://github.com/tidyverse/readxl/pull/687/commits/9884b53341e475ec984ebe2ff1182ff1347d06ad
i.e. for compilation on Alpine the two headers need to be first so that the types get defined
=> Fix compilation on Alpine Linux (redux)

vignettes/articles/column-names.Rmd
Currently the link leads to [principles.tidyverse.org](https://principles.tidyverse.org/names-attribute.html), which is no longer active. The tidy design principles guide is now found at [design.tidyverse.org](https://design.tidyverse.org/names.html).
=> Fix link to tidyverse design principles

vignettes/articles/readxl-workflows.Rmd
=> Updating use of superceded map_df to map %>% list_rbind

src/zip.cpp
cpp11 allows some somewhat scary implicit conversions between `sexp` and the 3 types `bool`, `size_t`, and `double`. These are unchecked conversions, and we'd like to remove them:
https://github.com/r-lib/cpp11/pull/390/
The recommended way is to use `cpp11::as_cpp<bool>()`, which checks the type and length before performing the conversion.
I'm not going to remove these in this version of cpp11, but we will in the next
=> Avoid scary implicit conversion from `sexp` to `bool`

.github/workflows/rhub.yaml, src/libxls/xls.c, src/libxls/xlsstruct.h
Closes #769, closes #770
*This journey went through a CI rough patch due to changes in r-devel around LAPACK/BLAS. For the purposes of getting to green (for specific checks and most especially for `gcc-asan`) @gaborcsardi temporarily reverted a couple of containers (including `gcc-asan`) back to their versions from a week ago.*
=> Fix sanitizer warning
